CREATE TABLE "BAKERY"."USERS" 
   (   "USERID" VARCHAR2(20 BYTE), 
   "USERPWD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "USERNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "AGE" NUMBER NOT NULL ENABLE, 
   "PHONE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "GRADE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "POINT" NUMBER NOT NULL ENABLE, 
    PRIMARY KEY ("USERID")
    
    
     CREATE TABLE "BAKERY"."PRODUCT" 
   (   "PRODUCTCODE" VARCHAR2(20 BYTE), 
   "PRODUCTNAME" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
   "FNAME" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
   "SELLPRICE" NUMBER NOT NULL ENABLE, 
   "DESCRIPTION" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
    PRIMARY KEY ("PRODUCTCODE")
    
    
    CREATE TABLE "BAKERY"."ORDERS" 
   (   "ORDERNO" NUMBER, 
   "ORDERDATE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "RECEIVINGDATE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "ORDERTOTAL" NUMBER NOT NULL ENABLE, 
   "ORDERSTATE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "USERID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    PRIMARY KEY ("ORDERNO")
    
    CREATE TABLE "BAKERY"."ORDER_DETAIL" 
   (   "ORDENO" NUMBER NOT NULL ENABLE, 
   "PRODUCTCODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
   "QUANTITY" NUMBER NOT NULL ENABLE, 
    CONSTRAINT "PK_ORDER_DETAIL" PRIMARY KEY ("ORDENO")
    